language: node_js
node_js: stable

cache:
  directories:
    - node_modules
before_install:
  - npm install hexo-cli -g

install:
  - npm install
  - npm install hexo-deployer-git --save
  - git clone https://github.com/zer0i3/hexo-theme-zob.git themes/zob

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "zer0i3"
  - git config user.email "i@aiyo.xyz"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/zer0i3/zer0i3.github.io.git